// 30-day curriculum.
// Sachi: please double-check the Japanese here for accuracy/naturalness — this was
// drafted from general beginner-Japanese knowledge, not verified by a native speaker.
// Quizzes intentionally use romaji only (never kana) since the learner can't read
// hiragana/katakana yet — kana only appears on the lesson flashcards for exposure.

const CURRICULUM = [
  {
    day: 1,
    title: "Day 1: Greetings",
    words: [
      { jp: "こんにちは", romaji: "konnichiwa", en: "hello" },
      { jp: "おはよう", romaji: "ohayou", en: "good morning" },
      { jp: "さようなら", romaji: "sayounara", en: "goodbye" },
      { jp: "ありがとう", romaji: "arigatou", en: "thank you" },
      { jp: "はい", romaji: "hai", en: "yes" },
      { jp: "いいえ", romaji: "iie", en: "no" },
    ],
    quiz: [
      { question: "How do you say 'hello'?", choices: ["konnichiwa", "sayounara", "arigatou", "hai"], answer: "konnichiwa" },
      { question: "How do you say 'thank you'?", choices: ["iie", "ohayou", "arigatou", "hai"], answer: "arigatou" },
      { question: "What does 'sayounara' mean?", choices: ["hello", "goodbye", "yes", "no"], answer: "goodbye" },
      { question: "What does 'ohayou' mean?", choices: ["good morning", "goodbye", "thank you", "no"], answer: "good morning" },
      { question: "How do you say 'yes'?", choices: ["iie", "hai", "arigatou", "konnichiwa"], answer: "hai" },
    ],
  },
  {
    day: 2,
    title: "Day 2: Numbers 1-5",
    words: [
      { jp: "いち", romaji: "ichi", en: "one (1)" },
      { jp: "に", romaji: "ni", en: "two (2)" },
      { jp: "さん", romaji: "san", en: "three (3)" },
      { jp: "よん", romaji: "yon", en: "four (4)" },
      { jp: "ご", romaji: "go", en: "five (5)" },
    ],
    quiz: [
      { question: "How do you say the number 1?", choices: ["ichi", "ni", "san", "go"], answer: "ichi" },
      { question: "How do you say the number 4?", choices: ["yon", "san", "go", "ni"], answer: "yon" },
      { question: "What does 'go' mean?", choices: ["four (4)", "five (5)", "two (2)", "one (1)"], answer: "five (5)" },
      { question: "What does 'san' mean?", choices: ["three (3)", "two (2)", "five (5)", "four (4)"], answer: "three (3)" },
      { question: "How do you say the number 2?", choices: ["ni", "ichi", "yon", "san"], answer: "ni" },
    ],
  },
  {
    day: 3,
    title: "Day 3: Numbers 6-10",
    words: [
      { jp: "ろく", romaji: "roku", en: "six (6)" },
      { jp: "なな", romaji: "nana", en: "seven (7)" },
      { jp: "はち", romaji: "hachi", en: "eight (8)" },
      { jp: "きゅう", romaji: "kyuu", en: "nine (9)" },
      { jp: "じゅう", romaji: "juu", en: "ten (10)" },
    ],
    quiz: [
      { question: "How do you say the number 10?", choices: ["juu", "kyuu", "hachi", "roku"], answer: "juu" },
      { question: "What does 'hachi' mean?", choices: ["six (6)", "seven (7)", "eight (8)", "nine (9)"], answer: "eight (8)" },
      { question: "How do you say the number 7?", choices: ["nana", "roku", "juu", "kyuu"], answer: "nana" },
      { question: "What does 'kyuu' mean?", choices: ["nine (9)", "ten (10)", "six (6)", "eight (8)"], answer: "nine (9)" },
      { question: "How do you say the number 6?", choices: ["roku", "nana", "hachi", "juu"], answer: "roku" },
    ],
  },
  {
    day: 4,
    title: "Day 4: Self-Introduction",
    words: [
      { jp: "わたし", romaji: "watashi", en: "I / me" },
      { jp: "なまえ", romaji: "namae", en: "name" },
      { jp: "です", romaji: "desu", en: "am / is (polite)" },
      { jp: "はじめまして", romaji: "hajimemashite", en: "nice to meet you (on first meeting)" },
      { jp: "よろしくおねがいします", romaji: "yoroshiku onegaishimasu", en: "please be kind to me (said after introducing yourself)" },
      { jp: "あなた", romaji: "anata", en: "you" },
    ],
    quiz: [
      { question: "How do you say 'I / me'?", choices: ["watashi", "anata", "namae", "desu"], answer: "watashi" },
      { question: "What does 'hajimemashite' mean?", choices: ["thank you", "nice to meet you", "goodbye", "my name is"], answer: "nice to meet you" },
      { question: "How do you say 'name'?", choices: ["namae", "watashi", "anata", "desu"], answer: "namae" },
      { question: "What does 'anata' mean?", choices: ["I / me", "you", "name", "is / am"], answer: "you" },
      { question: "How do you say the polite phrase after introducing yourself?", choices: ["yoroshiku onegaishimasu", "hajimemashite", "arigatou", "sumimasen"], answer: "yoroshiku onegaishimasu" },
    ],
  },
  {
    day: 5,
    title: "Day 5: Politeness Words",
    words: [
      { jp: "すみません", romaji: "sumimasen", en: "excuse me / sorry" },
      { jp: "ごめんなさい", romaji: "gomennasai", en: "I'm sorry" },
      { jp: "おねがいします", romaji: "onegaishimasu", en: "please" },
      { jp: "だいじょうぶ", romaji: "daijoubu", en: "it's okay / fine" },
      { jp: "げんき", romaji: "genki", en: "energetic / well" },
      { jp: "またね", romaji: "mata ne", en: "see you later" },
    ],
    quiz: [
      { question: "How do you say 'excuse me / sorry'?", choices: ["sumimasen", "onegaishimasu", "daijoubu", "genki"], answer: "sumimasen" },
      { question: "What does 'daijoubu' mean?", choices: ["please", "it's okay / fine", "sorry", "see you later"], answer: "it's okay / fine" },
      { question: "How do you say 'please'?", choices: ["onegaishimasu", "gomennasai", "mata ne", "genki"], answer: "onegaishimasu" },
      { question: "What does 'mata ne' mean?", choices: ["I'm sorry", "see you later", "excuse me", "well / energetic"], answer: "see you later" },
      { question: "How do you say 'I'm sorry'?", choices: ["gomennasai", "sumimasen", "daijoubu", "onegaishimasu"], answer: "gomennasai" },
    ],
  },
  {
    day: 6,
    title: "Day 6: Adjectives",
    words: [
      { jp: "おいしい", romaji: "oishii", en: "delicious" },
      { jp: "かわいい", romaji: "kawaii", en: "cute" },
      { jp: "おおきい", romaji: "ookii", en: "big" },
      { jp: "ちいさい", romaji: "chiisai", en: "small" },
      { jp: "あつい", romaji: "atsui", en: "hot" },
      { jp: "さむい", romaji: "samui", en: "cold" },
    ],
    quiz: [
      { question: "How do you say 'delicious'?", choices: ["oishii", "kawaii", "ookii", "samui"], answer: "oishii" },
      { question: "What does 'chiisai' mean?", choices: ["big", "small", "hot", "cold"], answer: "small" },
      { question: "How do you say 'cute'?", choices: ["kawaii", "oishii", "atsui", "chiisai"], answer: "kawaii" },
      { question: "What does 'atsui' mean?", choices: ["cold", "small", "hot", "big"], answer: "hot" },
      { question: "How do you say 'big'?", choices: ["ookii", "chiisai", "samui", "kawaii"], answer: "ookii" },
    ],
  },
  {
    day: 7,
    title: "Day 7: Week 1 Review",
    words: [
      { jp: "こんにちは", romaji: "konnichiwa", en: "hello" },
      { jp: "ありがとう", romaji: "arigatou", en: "thank you" },
      { jp: "いち", romaji: "ichi", en: "one (1)" },
      { jp: "なまえ", romaji: "namae", en: "name" },
      { jp: "すみません", romaji: "sumimasen", en: "excuse me / sorry" },
      { jp: "おいしい", romaji: "oishii", en: "delicious" },
    ],
    quiz: [
      { question: "How do you say 'hello'?", choices: ["konnichiwa", "arigatou", "sumimasen", "oishii"], answer: "konnichiwa" },
      { question: "What does 'namae' mean?", choices: ["name", "thank you", "one (1)", "delicious"], answer: "name" },
      { question: "How do you say 'thank you'?", choices: ["arigatou", "konnichiwa", "ichi", "sumimasen"], answer: "arigatou" },
      { question: "What does 'sumimasen' mean?", choices: ["hello", "excuse me / sorry", "delicious", "name"], answer: "excuse me / sorry" },
      { question: "How do you say the number 1?", choices: ["ichi", "namae", "oishii", "arigatou"], answer: "ichi" },
    ],
  },
  {
    day: 8,
    title: "Day 8: Family Words",
    words: [
      { jp: "おかあさん", romaji: "okaasan", en: "mother" },
      { jp: "おとうさん", romaji: "otousan", en: "father" },
      { jp: "むすこ", romaji: "musuko", en: "son" },
      { jp: "かぞく", romaji: "kazoku", en: "family" },
      { jp: "あかちゃん", romaji: "akachan", en: "baby" },
      { jp: "こども", romaji: "kodomo", en: "child" },
    ],
    quiz: [
      { question: "How do you say 'mother'?", choices: ["okaasan", "otousan", "musuko", "kodomo"], answer: "okaasan" },
      { question: "What does 'musuko' mean?", choices: ["father", "son", "family", "baby"], answer: "son" },
      { question: "How do you say 'family'?", choices: ["kazoku", "kodomo", "akachan", "otousan"], answer: "kazoku" },
      { question: "What does 'akachan' mean?", choices: ["child", "baby", "mother", "son"], answer: "baby" },
      { question: "How do you say 'father'?", choices: ["otousan", "okaasan", "musuko", "kazoku"], answer: "otousan" },
    ],
  },
  {
    day: 9,
    title: "Day 9: More Family & Friends",
    words: [
      { jp: "つま", romaji: "tsuma", en: "wife" },
      { jp: "おっと", romaji: "otto", en: "husband" },
      { jp: "おばあちゃん", romaji: "obaachan", en: "grandma" },
      { jp: "おじいちゃん", romaji: "ojiichan", en: "grandpa" },
      { jp: "ともだち", romaji: "tomodachi", en: "friend" },
      { jp: "ひと", romaji: "hito", en: "person" },
    ],
    quiz: [
      { question: "How do you say 'wife'?", choices: ["tsuma", "otto", "obaachan", "hito"], answer: "tsuma" },
      { question: "What does 'tomodachi' mean?", choices: ["person", "friend", "husband", "grandpa"], answer: "friend" },
      { question: "How do you say 'husband'?", choices: ["otto", "tsuma", "ojiichan", "hito"], answer: "otto" },
      { question: "What does 'obaachan' mean?", choices: ["grandpa", "grandma", "wife", "friend"], answer: "grandma" },
      { question: "How do you say 'grandpa'?", choices: ["ojiichan", "obaachan", "otto", "tomodachi"], answer: "ojiichan" },
    ],
  },
  {
    day: 10,
    title: "Day 10: Daily Routine Verbs",
    words: [
      { jp: "たべる", romaji: "taberu", en: "to eat" },
      { jp: "ねる", romaji: "neru", en: "to sleep" },
      { jp: "おきる", romaji: "okiru", en: "to wake up" },
      { jp: "あそぶ", romaji: "asobu", en: "to play" },
      { jp: "なく", romaji: "naku", en: "to cry" },
      { jp: "わらう", romaji: "warau", en: "to laugh" },
    ],
    quiz: [
      { question: "How do you say 'to eat'?", choices: ["taberu", "neru", "okiru", "asobu"], answer: "taberu" },
      { question: "What does 'naku' mean?", choices: ["to laugh", "to cry", "to sleep", "to play"], answer: "to cry" },
      { question: "How do you say 'to sleep'?", choices: ["neru", "okiru", "taberu", "warau"], answer: "neru" },
      { question: "What does 'asobu' mean?", choices: ["to wake up", "to play", "to eat", "to cry"], answer: "to play" },
      { question: "How do you say 'to laugh'?", choices: ["warau", "naku", "neru", "okiru"], answer: "warau" },
    ],
  },
  {
    day: 11,
    title: "Day 11: Time Words",
    words: [
      { jp: "あさ", romaji: "asa", en: "morning" },
      { jp: "ひる", romaji: "hiru", en: "noon / daytime" },
      { jp: "よる", romaji: "yoru", en: "night" },
      { jp: "きょう", romaji: "kyou", en: "today" },
      { jp: "あした", romaji: "ashita", en: "tomorrow" },
      { jp: "いま", romaji: "ima", en: "now" },
    ],
    quiz: [
      { question: "How do you say 'morning'?", choices: ["asa", "hiru", "yoru", "ima"], answer: "asa" },
      { question: "What does 'ashita' mean?", choices: ["today", "tomorrow", "now", "night"], answer: "tomorrow" },
      { question: "How do you say 'night'?", choices: ["yoru", "asa", "hiru", "kyou"], answer: "yoru" },
      { question: "What does 'kyou' mean?", choices: ["tomorrow", "today", "now", "morning"], answer: "today" },
      { question: "How do you say 'now'?", choices: ["ima", "kyou", "ashita", "hiru"], answer: "ima" },
    ],
  },
  {
    day: 12,
    title: "Day 12: More Time Words",
    words: [
      { jp: "いつ", romaji: "itsu", en: "when" },
      { jp: "なんじ", romaji: "nanji", en: "what time" },
      { jp: "じ", romaji: "ji", en: "o'clock" },
      { jp: "まいにち", romaji: "mainichi", en: "every day" },
      { jp: "すぐ", romaji: "sugu", en: "soon / right away" },
      { jp: "もう", romaji: "mou", en: "already" },
    ],
    quiz: [
      { question: "How do you say 'when'?", choices: ["itsu", "nanji", "mainichi", "sugu"], answer: "itsu" },
      { question: "What does 'nanji' mean?", choices: ["already", "what time", "every day", "soon"], answer: "what time" },
      { question: "How do you say 'every day'?", choices: ["mainichi", "itsu", "ji", "mou"], answer: "mainichi" },
      { question: "What does 'sugu' mean?", choices: ["already", "soon / right away", "when", "o'clock"], answer: "soon / right away" },
      { question: "How do you say 'already'?", choices: ["mou", "sugu", "itsu", "nanji"], answer: "mou" },
    ],
  },
  {
    day: 13,
    title: "Day 13: Daily Phrases",
    words: [
      { jp: "おはようございます", romaji: "ohayou gozaimasu", en: "good morning (polite)" },
      { jp: "おやすみ", romaji: "oyasumi", en: "goodnight" },
      { jp: "いただきます", romaji: "itadakimasu", en: "said before eating" },
      { jp: "ごちそうさま", romaji: "gochisousama", en: "said after eating" },
      { jp: "ただいま", romaji: "tadaima", en: "I'm home" },
      { jp: "おかえり", romaji: "okaeri", en: "welcome home" },
    ],
    quiz: [
      { question: "How do you say 'I'm home'?", choices: ["tadaima", "okaeri", "oyasumi", "itadakimasu"], answer: "tadaima" },
      { question: "What does 'okaeri' mean?", choices: ["I'm home", "welcome home", "goodnight", "good morning"], answer: "welcome home" },
      { question: "What do you say before eating?", choices: ["itadakimasu", "gochisousama", "tadaima", "oyasumi"], answer: "itadakimasu" },
      { question: "What does 'gochisousama' mean?", choices: ["said before eating", "said after eating", "goodnight", "I'm home"], answer: "said after eating" },
      { question: "How do you say 'goodnight'?", choices: ["oyasumi", "ohayou gozaimasu", "okaeri", "tadaima"], answer: "oyasumi" },
    ],
  },
  {
    day: 14,
    title: "Day 14: Week 2 Review",
    words: [
      { jp: "おかあさん", romaji: "okaasan", en: "mother" },
      { jp: "むすこ", romaji: "musuko", en: "son" },
      { jp: "たべる", romaji: "taberu", en: "to eat" },
      { jp: "あした", romaji: "ashita", en: "tomorrow" },
      { jp: "なんじ", romaji: "nanji", en: "what time" },
      { jp: "ただいま", romaji: "tadaima", en: "I'm home" },
    ],
    quiz: [
      { question: "How do you say 'mother'?", choices: ["okaasan", "musuko", "taberu", "tadaima"], answer: "okaasan" },
      { question: "What does 'ashita' mean?", choices: ["today", "tomorrow", "what time", "son"], answer: "tomorrow" },
      { question: "How do you say 'to eat'?", choices: ["taberu", "okaasan", "nanji", "ashita"], answer: "taberu" },
      { question: "What does 'tadaima' mean?", choices: ["I'm home", "what time", "mother", "son"], answer: "I'm home" },
      { question: "How do you say 'son'?", choices: ["musuko", "okaasan", "taberu", "nanji"], answer: "musuko" },
    ],
  },
  {
    day: 15,
    title: "Day 15: Food Vocabulary",
    words: [
      { jp: "ごはん", romaji: "gohan", en: "rice / meal" },
      { jp: "みず", romaji: "mizu", en: "water" },
      { jp: "さかな", romaji: "sakana", en: "fish" },
      { jp: "にく", romaji: "niku", en: "meat" },
      { jp: "やさい", romaji: "yasai", en: "vegetable" },
      { jp: "くだもの", romaji: "kudamono", en: "fruit" },
    ],
    quiz: [
      { question: "How do you say 'rice / meal'?", choices: ["gohan", "mizu", "sakana", "niku"], answer: "gohan" },
      { question: "What does 'yasai' mean?", choices: ["fruit", "vegetable", "meat", "fish"], answer: "vegetable" },
      { question: "How do you say 'water'?", choices: ["mizu", "gohan", "kudamono", "niku"], answer: "mizu" },
      { question: "What does 'sakana' mean?", choices: ["meat", "fish", "vegetable", "rice / meal"], answer: "fish" },
      { question: "How do you say 'fruit'?", choices: ["kudamono", "yasai", "sakana", "mizu"], answer: "kudamono" },
    ],
  },
  {
    day: 16,
    title: "Day 16: Taste & Food Words",
    words: [
      { jp: "あまい", romaji: "amai", en: "sweet" },
      { jp: "からい", romaji: "karai", en: "spicy" },
      { jp: "すき", romaji: "suki", en: "like" },
      { jp: "きらい", romaji: "kirai", en: "dislike" },
      { jp: "たべもの", romaji: "tabemono", en: "food" },
      { jp: "のみもの", romaji: "nomimono", en: "drink" },
    ],
    quiz: [
      { question: "How do you say 'sweet'?", choices: ["amai", "karai", "suki", "kirai"], answer: "amai" },
      { question: "What does 'kirai' mean?", choices: ["like", "dislike", "spicy", "sweet"], answer: "dislike" },
      { question: "How do you say 'spicy'?", choices: ["karai", "amai", "tabemono", "nomimono"], answer: "karai" },
      { question: "What does 'nomimono' mean?", choices: ["food", "drink", "sweet", "like"], answer: "drink" },
      { question: "How do you say 'like'?", choices: ["suki", "kirai", "amai", "karai"], answer: "suki" },
    ],
  },
  {
    day: 17,
    title: "Day 17: Restaurant Phrases",
    words: [
      { jp: "メニュー", romaji: "menyuu", en: "menu" },
      { jp: "ください", romaji: "kudasai", en: "please give me" },
      { jp: "いくら", romaji: "ikura", en: "how much (cost)" },
      { jp: "おいしかった", romaji: "oishikatta", en: "it was delicious" },
      { jp: "おかいけい", romaji: "okaikei", en: "the check / bill" },
      { jp: "いらっしゃいませ", romaji: "irasshaimase", en: "welcome (said by shop staff)" },
    ],
    quiz: [
      { question: "How do you say 'please give me'?", choices: ["kudasai", "ikura", "menyuu", "okaikei"], answer: "kudasai" },
      { question: "What does 'ikura' mean?", choices: ["menu", "how much (cost)", "the check", "welcome"], answer: "how much (cost)" },
      { question: "How do you say 'menu'?", choices: ["menyuu", "kudasai", "okaikei", "ikura"], answer: "menyuu" },
      { question: "What does 'okaikei' mean?", choices: ["the check / bill", "menu", "welcome", "delicious"], answer: "the check / bill" },
      { question: "How do you say 'it was delicious'?", choices: ["oishikatta", "kudasai", "ikura", "irasshaimase"], answer: "oishikatta" },
    ],
  },
  {
    day: 18,
    title: "Day 18: Hunger & Preferences",
    words: [
      { jp: "たべたい", romaji: "tabetai", en: "want to eat" },
      { jp: "のみたい", romaji: "nomitai", en: "want to drink" },
      { jp: "おなかがすいた", romaji: "onaka ga suita", en: "I'm hungry" },
      { jp: "のどがかわいた", romaji: "nodo ga kawaita", en: "I'm thirsty" },
      { jp: "すきです", romaji: "suki desu", en: "I like it" },
      { jp: "きらいです", romaji: "kirai desu", en: "I dislike it" },
    ],
    quiz: [
      { question: "How do you say 'I'm hungry'?", choices: ["onaka ga suita", "nodo ga kawaita", "tabetai", "nomitai"], answer: "onaka ga suita" },
      { question: "What does 'nomitai' mean?", choices: ["want to eat", "want to drink", "I'm thirsty", "I like it"], answer: "want to drink" },
      { question: "How do you say 'I'm thirsty'?", choices: ["nodo ga kawaita", "onaka ga suita", "suki desu", "kirai desu"], answer: "nodo ga kawaita" },
      { question: "What does 'suki desu' mean?", choices: ["I dislike it", "I like it", "want to eat", "I'm hungry"], answer: "I like it" },
      { question: "How do you say 'want to eat'?", choices: ["tabetai", "nomitai", "kirai desu", "suki desu"], answer: "tabetai" },
    ],
  },
  {
    day: 19,
    title: "Day 19: Drinks",
    words: [
      { jp: "おちゃ", romaji: "ocha", en: "tea" },
      { jp: "コーヒー", romaji: "koohii", en: "coffee" },
      { jp: "ビール", romaji: "biiru", en: "beer" },
      { jp: "ジュース", romaji: "juusu", en: "juice" },
      { jp: "ぎゅうにゅう", romaji: "gyuunyuu", en: "milk" },
      { jp: "かんぱい", romaji: "kanpai", en: "cheers!" },
    ],
    quiz: [
      { question: "How do you say 'coffee'?", choices: ["koohii", "ocha", "biiru", "juusu"], answer: "koohii" },
      { question: "What does 'gyuunyuu' mean?", choices: ["juice", "milk", "beer", "tea"], answer: "milk" },
      { question: "How do you say 'tea'?", choices: ["ocha", "koohii", "kanpai", "biiru"], answer: "ocha" },
      { question: "What does 'kanpai' mean?", choices: ["cheers!", "milk", "juice", "coffee"], answer: "cheers!" },
      { question: "How do you say 'juice'?", choices: ["juusu", "biiru", "gyuunyuu", "ocha"], answer: "juusu" },
    ],
  },
  {
    day: 20,
    title: "Day 20: Asking About Things",
    words: [
      { jp: "これ", romaji: "kore", en: "this" },
      { jp: "それ", romaji: "sore", en: "that" },
      { jp: "あれ", romaji: "are", en: "that (over there)" },
      { jp: "なん", romaji: "nan", en: "what" },
      { jp: "ほしい", romaji: "hoshii", en: "want (an object)" },
      { jp: "たかい", romaji: "takai", en: "expensive" },
    ],
    quiz: [
      { question: "How do you say 'this'?", choices: ["kore", "sore", "are", "nan"], answer: "kore" },
      { question: "What does 'are' mean?", choices: ["this", "that", "that (over there)", "what"], answer: "that (over there)" },
      { question: "How do you say 'what'?", choices: ["nan", "kore", "hoshii", "takai"], answer: "nan" },
      { question: "What does 'hoshii' mean?", choices: ["expensive", "want (an object)", "this", "that"], answer: "want (an object)" },
      { question: "How do you say 'expensive'?", choices: ["takai", "hoshii", "nan", "sore"], answer: "takai" },
    ],
  },
  {
    day: 21,
    title: "Day 21: Week 3 Review",
    words: [
      { jp: "ごはん", romaji: "gohan", en: "rice / meal" },
      { jp: "すき", romaji: "suki", en: "like" },
      { jp: "ください", romaji: "kudasai", en: "please give me" },
      { jp: "おなかがすいた", romaji: "onaka ga suita", en: "I'm hungry" },
      { jp: "コーヒー", romaji: "koohii", en: "coffee" },
      { jp: "ほしい", romaji: "hoshii", en: "want (an object)" },
    ],
    quiz: [
      { question: "How do you say 'rice / meal'?", choices: ["gohan", "suki", "kudasai", "koohii"], answer: "gohan" },
      { question: "What does 'hoshii' mean?", choices: ["like", "want (an object)", "coffee", "please give me"], answer: "want (an object)" },
      { question: "How do you say 'please give me'?", choices: ["kudasai", "gohan", "suki", "hoshii"], answer: "kudasai" },
      { question: "What does 'onaka ga suita' mean?", choices: ["I'm thirsty", "I'm hungry", "I like it", "I want it"], answer: "I'm hungry" },
      { question: "How do you say 'coffee'?", choices: ["koohii", "gohan", "kudasai", "suki"], answer: "koohii" },
    ],
  },
  {
    day: 22,
    title: "Day 22: Directions",
    words: [
      { jp: "みぎ", romaji: "migi", en: "right" },
      { jp: "ひだり", romaji: "hidari", en: "left" },
      { jp: "まっすぐ", romaji: "massugu", en: "straight" },
      { jp: "ここ", romaji: "koko", en: "here" },
      { jp: "そこ", romaji: "soko", en: "there" },
      { jp: "どこ", romaji: "doko", en: "where" },
    ],
    quiz: [
      { question: "How do you say 'right'?", choices: ["migi", "hidari", "massugu", "koko"], answer: "migi" },
      { question: "What does 'doko' mean?", choices: ["here", "there", "where", "straight"], answer: "where" },
      { question: "How do you say 'left'?", choices: ["hidari", "migi", "soko", "doko"], answer: "hidari" },
      { question: "What does 'massugu' mean?", choices: ["right", "left", "straight", "here"], answer: "straight" },
      { question: "How do you say 'here'?", choices: ["koko", "soko", "doko", "migi"], answer: "koko" },
    ],
  },
  {
    day: 23,
    title: "Day 23: Places",
    words: [
      { jp: "えき", romaji: "eki", en: "station" },
      { jp: "トイレ", romaji: "toire", en: "toilet / bathroom" },
      { jp: "びょういん", romaji: "byouin", en: "hospital" },
      { jp: "くうこう", romaji: "kuukou", en: "airport" },
      { jp: "いえ", romaji: "ie", en: "house" },
      { jp: "がっこう", romaji: "gakkou", en: "school" },
    ],
    quiz: [
      { question: "How do you say 'station'?", choices: ["eki", "toire", "byouin", "kuukou"], answer: "eki" },
      { question: "What does 'gakkou' mean?", choices: ["house", "school", "hospital", "airport"], answer: "school" },
      { question: "How do you say 'bathroom'?", choices: ["toire", "eki", "ie", "gakkou"], answer: "toire" },
      { question: "What does 'kuukou' mean?", choices: ["station", "hospital", "airport", "house"], answer: "airport" },
      { question: "How do you say 'house'?", choices: ["ie", "eki", "byouin", "toire"], answer: "ie" },
    ],
  },
  {
    day: 24,
    title: "Day 24: Common Verbs",
    words: [
      { jp: "いく", romaji: "iku", en: "to go" },
      { jp: "くる", romaji: "kuru", en: "to come" },
      { jp: "かえる", romaji: "kaeru", en: "to return / go home" },
      { jp: "みる", romaji: "miru", en: "to see / watch" },
      { jp: "きく", romaji: "kiku", en: "to listen / ask" },
      { jp: "はなす", romaji: "hanasu", en: "to speak" },
    ],
    quiz: [
      { question: "How do you say 'to go'?", choices: ["iku", "kuru", "kaeru", "miru"], answer: "iku" },
      { question: "What does 'hanasu' mean?", choices: ["to listen", "to speak", "to see", "to come"], answer: "to speak" },
      { question: "How do you say 'to come'?", choices: ["kuru", "iku", "kaeru", "kiku"], answer: "kuru" },
      { question: "What does 'miru' mean?", choices: ["to see / watch", "to listen", "to speak", "to return"], answer: "to see / watch" },
      { question: "How do you say 'to return / go home'?", choices: ["kaeru", "iku", "kuru", "hanasu"], answer: "kaeru" },
    ],
  },
  {
    day: 25,
    title: "Day 25: Useful Phrases",
    words: [
      { jp: "わかります", romaji: "wakarimasu", en: "I understand" },
      { jp: "わかりません", romaji: "wakarimasen", en: "I don't understand" },
      { jp: "もういちど", romaji: "mou ichido", en: "one more time" },
      { jp: "ゆっくり", romaji: "yukkuri", en: "slowly" },
      { jp: "えいご", romaji: "eigo", en: "English" },
      { jp: "にほんご", romaji: "nihongo", en: "Japanese (language)" },
    ],
    quiz: [
      { question: "How do you say 'I don't understand'?", choices: ["wakarimasen", "wakarimasu", "yukkuri", "mou ichido"], answer: "wakarimasen" },
      { question: "What does 'yukkuri' mean?", choices: ["slowly", "one more time", "English", "I understand"], answer: "slowly" },
      { question: "How do you say 'one more time'?", choices: ["mou ichido", "yukkuri", "eigo", "nihongo"], answer: "mou ichido" },
      { question: "What does 'nihongo' mean?", choices: ["English", "Japanese (language)", "I understand", "slowly"], answer: "Japanese (language)" },
      { question: "How do you say 'I understand'?", choices: ["wakarimasu", "wakarimasen", "eigo", "mou ichido"], answer: "wakarimasu" },
    ],
  },
  {
    day: 26,
    title: "Day 26: Numbers & Money",
    words: [
      { jp: "ひゃく", romaji: "hyaku", en: "hundred (100)" },
      { jp: "せん", romaji: "sen", en: "thousand (1,000)" },
      { jp: "えん", romaji: "en", en: "yen" },
      { jp: "ぜんぶで", romaji: "zenbu de", en: "in total" },
      { jp: "たかい", romaji: "takai", en: "expensive" },
      { jp: "やすい", romaji: "yasui", en: "cheap" },
    ],
    quiz: [
      { question: "How do you say 'hundred (100)'?", choices: ["hyaku", "sen", "en", "yasui"], answer: "hyaku" },
      { question: "What does 'yasui' mean?", choices: ["expensive", "cheap", "in total", "yen"], answer: "cheap" },
      { question: "How do you say 'thousand (1,000)'?", choices: ["sen", "hyaku", "en", "zenbu de"], answer: "sen" },
      { question: "What does 'zenbu de' mean?", choices: ["in total", "yen", "cheap", "expensive"], answer: "in total" },
      { question: "How do you say 'expensive'?", choices: ["takai", "yasui", "sen", "hyaku"], answer: "takai" },
    ],
  },
  {
    day: 27,
    title: "Day 27: Weather",
    words: [
      { jp: "てんき", romaji: "tenki", en: "weather" },
      { jp: "あめ", romaji: "ame", en: "rain" },
      { jp: "はれ", romaji: "hare", en: "sunny" },
      { jp: "くもり", romaji: "kumori", en: "cloudy" },
      { jp: "かぜ", romaji: "kaze", en: "wind" },
      { jp: "ゆき", romaji: "yuki", en: "snow" },
    ],
    quiz: [
      { question: "How do you say 'rain'?", choices: ["ame", "hare", "kumori", "yuki"], answer: "ame" },
      { question: "What does 'kaze' mean?", choices: ["snow", "wind", "sunny", "weather"], answer: "wind" },
      { question: "How do you say 'sunny'?", choices: ["hare", "ame", "kumori", "kaze"], answer: "hare" },
      { question: "What does 'kumori' mean?", choices: ["cloudy", "snow", "rain", "wind"], answer: "cloudy" },
      { question: "How do you say 'snow'?", choices: ["yuki", "ame", "hare", "tenki"], answer: "yuki" },
    ],
  },
  {
    day: 28,
    title: "Day 28: Week 4 Review",
    words: [
      { jp: "みぎ", romaji: "migi", en: "right" },
      { jp: "えき", romaji: "eki", en: "station" },
      { jp: "いく", romaji: "iku", en: "to go" },
      { jp: "わかります", romaji: "wakarimasu", en: "I understand" },
      { jp: "たかい", romaji: "takai", en: "expensive" },
      { jp: "あめ", romaji: "ame", en: "rain" },
    ],
    quiz: [
      { question: "How do you say 'right'?", choices: ["migi", "eki", "iku", "ame"], answer: "migi" },
      { question: "What does 'wakarimasu' mean?", choices: ["I don't understand", "I understand", "expensive", "station"], answer: "I understand" },
      { question: "How do you say 'to go'?", choices: ["iku", "migi", "takai", "eki"], answer: "iku" },
      { question: "What does 'ame' mean?", choices: ["rain", "station", "right", "expensive"], answer: "rain" },
      { question: "How do you say 'station'?", choices: ["eki", "migi", "iku", "wakarimasu"], answer: "eki" },
    ],
  },
  {
    day: 29,
    title: "Day 29: Cumulative Review",
    words: [
      { jp: "ありがとう", romaji: "arigatou", en: "thank you" },
      { jp: "かぞく", romaji: "kazoku", en: "family" },
      { jp: "たべもの", romaji: "tabemono", en: "food" },
      { jp: "どこ", romaji: "doko", en: "where" },
      { jp: "にほんご", romaji: "nihongo", en: "Japanese (language)" },
      { jp: "むすこ", romaji: "musuko", en: "son" },
    ],
    quiz: [
      { question: "How do you say 'thank you'?", choices: ["arigatou", "kazoku", "tabemono", "doko"], answer: "arigatou" },
      { question: "What does 'musuko' mean?", choices: ["family", "son", "food", "where"], answer: "son" },
      { question: "How do you say 'family'?", choices: ["kazoku", "arigatou", "nihongo", "doko"], answer: "kazoku" },
      { question: "What does 'doko' mean?", choices: ["where", "food", "family", "Japanese"], answer: "where" },
      { question: "How do you say 'food'?", choices: ["tabemono", "musuko", "kazoku", "nihongo"], answer: "tabemono" },
    ],
  },
  {
    day: 30,
    title: "Day 30: Final Challenge",
    words: [
      { jp: "わたしはウェスです。", romaji: "Watashi wa Wesu desu.", en: "I am Wes." },
      { jp: "にほんごをべんきょうしています。", romaji: "Nihongo wo benkyou shiteimasu.", en: "I am studying Japanese." },
      { jp: "むすこがだいすきです。", romaji: "Musuko ga daisuki desu.", en: "I love my son." },
      { jp: "がんばりました！", romaji: "Ganbarimashita!", en: "I did my best!" },
      { jp: "またあした！", romaji: "Mata ashita!", en: "See you tomorrow!" },
    ],
    quiz: [
      { question: "How do you say 'I am Wes'?", choices: ["Watashi wa Wesu desu.", "Nihongo wo benkyou shiteimasu.", "Mata ashita!", "Musuko ga daisuki desu."], answer: "Watashi wa Wesu desu." },
      { question: "What does 'Nihongo wo benkyou shiteimasu.' mean?", choices: ["I love my son", "I am studying Japanese", "I did my best", "See you tomorrow"], answer: "I am studying Japanese" },
      { question: "How do you say 'I love my son'?", choices: ["Musuko ga daisuki desu.", "Watashi wa Wesu desu.", "Ganbarimashita!", "Mata ashita!"], answer: "Musuko ga daisuki desu." },
      { question: "What does 'Ganbarimashita!' mean?", choices: ["See you tomorrow!", "I did my best!", "I am Wes", "I love my son"], answer: "I did my best!" },
      { question: "How do you say 'See you tomorrow!'?", choices: ["Mata ashita!", "Ganbarimashita!", "Nihongo wo benkyou shiteimasu.", "Watashi wa Wesu desu."], answer: "Mata ashita!" },
    ],
  },
];
